"""add label to user-settings and backfill values

Revision ID: 1fb5d1dd7e28
Revises: 89cc7b8cb451
Create Date: 2025-12-28 09:41:22.151936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from app.core.default_settings import DEFAULT_USER_SETTINGS, METADATA_SETTINGS, SettingMetadata

# revision identifiers, used by Alembic.
revision: str = '1fb5d1dd7e28'
down_revision: Union[str, None] = '89cc7b8cb451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    connection = op.get_bind()
    
    # Get all user IDs
    result = connection.execute(sa.text("SELECT id FROM users"))
    user_ids = [row[0] for row in result]
    
    # For each user, insert default settings that don't already exist
    for user_id in user_ids:
        for key, values_dict in DEFAULT_USER_SETTINGS.items():
            # Check if setting already exists
            existing = connection.execute(
                sa.text("""
                    SELECT id, label FROM user_settings 
                    WHERE user_id = :user_id AND key = :key
                """),
                {"user_id": user_id, "key": key}
            ).first()
            
            # Only insert if it doesn't exist
            if not existing:
                connection.execute(
                    sa.text("""
                        INSERT INTO user_settings (user_id, key, value)
                        VALUES (:user_id, :key, :value)
                    """),
                    {"user_id": user_id, "key": key, "value": values_dict["value"], "label": values_dict["label"]}
                )

            if existing:
                has_label = existing.label is not None
                if not has_label:
                    connection.execute(
                        sa.text("""
                            UPDATE user_settings SET label = :label, value = :value WHERE id = :id
                        """),
                        {"id": existing.id, "label": values_dict["label"], "value": values_dict["value"]}
                    )
 

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'label')
    # ### end Alembic commands ###
