"""add cascade rule to schedule_item

Revision ID: 3e75254707a3
Revises: 1845b178926f
Create Date: 2026-01-01 17:17:35.057685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e75254707a3'
down_revision: Union[str, None] = '1845b178926f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('schedule_items_task_id_fkey'), 'schedule_items', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_items', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_items', type_='foreignkey')
    op.create_foreign_key(op.f('schedule_items_task_id_fkey'), 'schedule_items', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
