"""add celery job structure

Revision ID: 4830093f7fc4
Revises: fb4f1d257e34
Create Date: 2026-01-05 21:34:02.734533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4830093f7fc4'
down_revision: Union[str, None] = 'fb4f1d257e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_celery_jobs_task_name'), 'celery_jobs', ['task_name'], unique=False)
    op.create_index(op.f('ix_celery_jobs_user_id'), 'celery_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_celery_jobs_user_id'), table_name='celery_jobs')
    op.drop_index(op.f('ix_celery_jobs_task_name'), table_name='celery_jobs')
    op.drop_table('celery_jobs')
    # ### end Alembic commands ###
