"""adjust schedule item for external sync

Revision ID: 76d26839d559
Revises: 1a248b4f780b
Create Date: 2026-03-13 07:43:53.387302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d26839d559'
down_revision: Union[str, None] = '1a248b4f780b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_items', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('schedule_items', sa.Column('connection_id', sa.Integer(), nullable=True))
    op.create_index('unique_external_id', 'schedule_items', ['user_id', 'source', 'external_id', 'connection_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL AND connection_id IS NOT NULL'))
    op.create_foreign_key(
        'fk_schedule_items_connection_id_calendar_connections',
        'schedule_items',
        'calendar_connections',
        ['connection_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_schedule_items_connection_id_calendar_connections',
        'schedule_items',
        type_='foreignkey',
    )
    op.drop_index('unique_external_id', table_name='schedule_items', postgresql_where=sa.text('external_id IS NOT NULL AND connection_id IS NOT NULL'))
    op.drop_column('schedule_items', 'connection_id')
    op.drop_column('schedule_items', 'external_id')
    # ### end Alembic commands ###
